title: JIHwan blog      "JiHwan": Unknown word
description: > # this means to ignore newlines until "baseurl:"
 저를 소개하는 블로그입니다.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jihonai.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: JiHwan
tagline: student
about-description: 탑레: 마스터 100점/ 대리문의: 010 5653 6266
pic: master.jfif # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: artemsheludko@tuta.io # Add your Email address
phone: 044 825 5523 # Add your Phone number
website: artemsheludko.pw # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: artemsheludko # Add your Github handle
twitter: '@artemsheludko_' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
