title: JIHwan blog
description: > # this means to ignore newlines until "baseurl:"
  새시즌 챌린저 도전
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jihonai.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: JiHwan
tagline: student
about-description: 탑레- 마스터 100점/ 대리문의- 010 5653 6266
pic: master.jpg # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: sinj87888@gmail.com  # Add your Email address
phone: 010 5653 6266 # Add your Phone number
website: artemsheludko.pw # Add your website, do not add http://  
linkedin: # Add your Linkedin handle
github: jihonai # Add your Github handle
instargram: 에잇 찌찌뽕 # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
